# Copyright (c) 2015 Ember
#
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

# Everything on the build machines is out of date.

language: cpp

git:
  depth: 1

branches:
  only:
    - master
    - development

compiler:
  - gcc
  - clang

env:
  global:
    - LIBSTDC_VERSION=4.9
    - GCC_VERSION=4.9
    - CLANG_VERSION=3.5

before_install:
    - if [ "$CXX" == "g++" ]; then sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test; fi

    - if [ "$CXX" == "clang++" ]; then echo "deb http://llvm.org/apt/precise/ llvm-toolchain-precise main" | sudo tee -a /etc/apt/sources.list; fi
    - if [ "$CXX" == "clang++" ]; then echo "deb http://llvm.org/apt/precise/ llvm-toolchain-precise-3.5 main" | sudo tee -a /etc/apt/sources.list; fi
    - if [ "$CXX" == "clang++" ]; then echo "deb http://ppa.launchpad.net/ubuntu-toolchain-r/test/ubuntu precise main" | sudo tee -a /etc/apt/sources.list; fi

    - sudo apt-get update -qq

install:
    - sudo apt-get install -y libmysqlcppconn-dev
    - sudo apt-get install -y libbotan1.10-dev

    - if [ "$CXX" == "g++" ]; then sudo apt-get install -qq -y g++-${GCC_VERSION}; fi
    - if [ "$CXX" == "g++" ]; then sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-${GCC_VERSION} 100; fi
    - if [ "$CXX" == "g++" ]; then sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-${GCC_VERSION} 100; fi

    - if [ "$CXX" == "clang++" ]; then sudo apt-get -qq -y --allow-unauthenticated install libstdc++-${LIBSTDC_VERSION}-dev; fi
    - if [ "$CXX" == "clang++" ]; then sudo apt-get -qq -y --allow-unauthenticated install clang-${CLANG_VERSION}; fi
    - if [ "$CXX" == "clang++" ]; then sudo update-alternatives --install /usr/bin/clang clang /usr/bin/clang-${CLANG_VERSION} 100; fi
    - if [ "$CXX" == "clang++" ]; then sudo update-alternatives --install /usr/bin/clang++ clang++ /usr/bin/clang++-${CLANG_VERSION} 100; fi

    - wget -O boost_1_58_0.tar.gz http://sourceforge.net/projects/boost/files/boost/1.58.0/boost_1_58_0.tar.gz/download
    - tar xzvf boost_1_58_0.tar.gz
    - cd boost_1_58_0/
    - sudo ./bootstrap.sh --with-libraries=system,filesystem,program_options
    - sudo ./b2 link=static install -j 2 cxxflags="-std=c++14"
    - cd ../
    - wget http://www.cmake.org/files/v3.2/cmake-3.2.3-Linux-x86_64.tar.gz
    - tar xzvf cmake-3.2.3-Linux-x86_64.tar.gz
    - sudo cp -r cmake-3.2.3-Linux-x86_64/* /usr/local

script:
    - mkdir build
    - cd build
    - cmake ../ -DCMAKE_BUILD_TYPE=Release -DBOTAN_ROOT_DOR=/usr/ -DBOTAN_INCLUDE_DIR=/usr/include/botan-1.10/ -DBOTAN_LIBRARY=/usr/lib/libbotan-1.10.so -DBOTAN_ROOT_DIR=/usr/
    - ./bin/unit_tests

notifications:
  irc:
    channels:
      - "irc.quakenet.org#ember"
    on_success: always
    on_failure: always