# Copyright (c) 2015 Ember
#
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

# Everything on the build machines is out of date.

language: cpp

git:
  depth: 1

branches:
  only:
    - master
    - development
    - coverity_scan

compiler:
  - gcc
  - clang

env:
  global:
    - LIBSTDC_VERSION=4.9
    - GCC_VERSION=4.9
    - CLANG_VERSION=3.5
    - secure: "QEjAwdyTIKC23olE3wKevwJT/wskkxedicR3BTsVIznC6gFhSilYDHQl7WZZnUygZpoCM2xGJVwb9d+CCultf5eLsJinJG3bR5wdAmtZeYcT8EwSVGqSexUQKxci/fxgISw/YTybIyT8j5f61tJ5/7bwouvhhBnYPlgcbU0QuzZRe4RD7F9bL9lzT18LeenecpnJseJFL9iUgRoiOYRQss7Zru1GcKfo89kWPdNsu8j49EqEpMQNRP9zQiyagGRwCVeTvDjd54mRedoUKciANiwKjjpqM0ZHZ9Ogpl44TV0EfPzT0jA10I46sliSYEoSNwvHx0JSAi02zXIJeww2rafYiCwiClXz7SWlJ2GAJVkUw7U12x0OJEArpyVrU7uJmPmFSuGNPI7F2mTM1OE80zN/iAUv6iARo7/Yo67ZOTSbl9YtFn5RpVA9fo0U+HSWAHZwIAHLn48BMwsgGjMPB0dqoEnc2jK7ayhMxxv+QoybQPXuAjy22kBEYjHuRpdglBJNkcFmgKprJOcqJR4/bkMv1XPPNptSPoXQgttoBCqQs+syFP13xFGtg7IUUBCnr6z5CiYktul9xTJWMUKFtpVjYJLk4lvkWSuW9ine4bZUvC3Yj9mcT2TjC2aN/inG9xZmGsQ/SnOgtt+Ou/6n8nPhnnuS7KN/A/CSEdzkhjo="

before_install:
    - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test

    - if [ "$CXX" == "clang++" ]; then echo "deb http://llvm.org/apt/precise/ llvm-toolchain-precise main" | sudo tee -a /etc/apt/sources.list; fi
    - if [ "$CXX" == "clang++" ]; then echo "deb http://llvm.org/apt/precise/ llvm-toolchain-precise-3.5 main" | sudo tee -a /etc/apt/sources.list; fi
    - if [ "$CXX" == "clang++" ]; then echo "deb http://ppa.launchpad.net/ubuntu-toolchain-r/test/ubuntu precise main" | sudo tee -a /etc/apt/sources.list; fi

    - sudo apt-get update -qq

install:
    - sudo apt-get install -y libbotan1.10-dev

    - if [ "$CXX" == "g++" ]; then sudo apt-get install -qq -y g++-${GCC_VERSION}; fi
    - if [ "$CXX" == "g++" ]; then sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-${GCC_VERSION} 100; fi
    - if [ "$CXX" == "g++" ]; then sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-${GCC_VERSION} 100; fi

    - if [ "$CXX" == "clang++" ]; then sudo apt-get -qq install build-essential; fi
    - if [ "$CXX" == "clang++" ]; then sudo apt-get -qq -y --allow-unauthenticated install libstdc++-${LIBSTDC_VERSION}-dev; fi
    - if [ "$CXX" == "clang++" ]; then sudo apt-get -qq -y --allow-unauthenticated install clang-${CLANG_VERSION}; fi
    - if [ "$CXX" == "clang++" ]; then sudo update-alternatives --install /usr/bin/clang clang /usr/bin/clang-${CLANG_VERSION} 1000; fi
    - if [ "$CXX" == "clang++" ]; then sudo update-alternatives --install /usr/bin/clang++ clang++ /usr/bin/clang++-${CLANG_VERSION} 1000; fi
    - if [ "$CXX" == "clang++" ]; then clang --version; fi
    - if [ "$CXX" == "clang++" ]; then export CC="clang-3.5"; fi
    - if [ "$CXX" == "clang++" ]; then export CXX="clang++-3.5"; fi

    - wget -O boost_1_58_0.tar.gz http://sourceforge.net/projects/boost/files/boost/1.58.0/boost_1_58_0.tar.gz/download
    - tar xzvf boost_1_58_0.tar.gz > /dev/null
    - cd boost_1_58_0/
    - if [ "$CXX" == "g++" ]; then sudo ./bootstrap.sh --with-libraries=system,filesystem,program_options; fi
    - if [ "$CXX" == "clang++-3.5" ]; then sudo ./bootstrap.sh --with-libraries=system,filesystem,program_options --with-toolset=clang; fi
    - sudo ./b2 link=static install -d0 -j 2 cxxflags="-std=c++14"
    - cd ../
    - wget http://www.cmake.org/files/v3.2/cmake-3.2.3-Linux-x86_64.tar.gz
    - tar xzvf cmake-3.2.3-Linux-x86_64.tar.gz
    - sudo cp -fR cmake-3.2.3-Linux-x86_64/* /usr
    - cmake --version
    - wget -O mysqlconn.tar.gz https://dev.mysql.com/get/Downloads/Connector-C++/mysql-connector-c++-1.1.6.tar.gz
    - tar xzvf mysqlconn.tar.gz > /dev/null
    - cd mysql-connector-c++-1.1.6/
    - cmake .
    - make clean
    - make
    - sudo make install
    - cd ../

script:
    - mkdir build
    - cd build
    - cmake ../ -DCMAKE_BUILD_TYPE=Release -DBOTAN_ROOT_DIR=/usr/ -DBOTAN_INCLUDE_DIR=/usr/include/botan-1.10/ -DBOTAN_LIBRARY=/usr/lib/libbotan-1.10.so -DBOTAN_ROOT_DIR=/usr/
    - make -j 2
    - ./bin/unit_tests

notifications:
  irc:
    channels:
      - "irc.quakenet.org#ember"
    on_success: never
    on_failure: always